### ISSUE TITLE
Exercise 2 - Write files using fs.createWriteStream

### ISSUE THREAD

**Issue by coderdiaz** [coderdiaz/bedu-node#3]
## Instructions
1. Create a web server using Node.js (Hint. `http.createServer`).
2. Get client requests for only `POST` http method.
3. Send data to `POST` request. For example, name, age, sex, etc.
4. Save data in `file` with the sent data.
5. Show the result in the `web` browser.

**Comment by davidtoris** [comment]
```js
const http  = require('http');
const url  = require('url');
const fs = require('fs');

const server = http.createServer((req, res) =>{

    const httpMethod = req.method;
    

    httpMethod.POST
        res.writeHead(200, {
            'Content-Type': 'application/json',
        });
        const data = fs.readFileSync('./data.json');
        res.write(data);
        
        const fecha = Date.now();
        const writer = fs.createWriteStream(fecha + '-datos.txt');
        writer.write(data, 'UTF8')
        writer.end()
        
        
        return res.end();

    

});

server.listen(8081, ()=>{
    console.log('listening on port 8081');
});
```

**Comment by coderdiaz** [comment]
> ```js
> const http  = require('http');
> const url  = require('url');
> const fs = require('fs');
> 
> const server = http.createServer((req, res) =>{
> 
>     const httpMethod = req.method;
>     
> 
>     httpMethod.POST
>         res.writeHead(200, {
>             'Content-Type': 'application/json',
>         });
>         const data = fs.readFileSync('./data.json');
>         res.write(data);
>         
>         const fecha = Date.now();
>         const writer = fs.createWriteStream(fecha + '-datos.txt');
>         writer.write(data, 'UTF8')
>         writer.end()
>         
>         
>         return res.end();
> 
>     
> 
> });
> 
> server.listen(8081, ()=>{
>     console.log('listening on port 8081');
> });
> ```

Please add the `step 5` 👍

**Comment by alankimo** [comment]
#4
